DROP TABLE CHAT;
DROP SEQUENCE CHATSEQ;

CREATE SEQUENCE CHATSEQ;
CREATE TABLE CHAT (

	CHAT_SEQ			INT				PRIMARY KEY,
	CHANNEL_NUM			INT				NOT NULL,
	MEMBER_ID			VARCHAR2(50)	NOT NULL,
	MEMBER_NAME       	VARCHAR2(20)	NOT NULL,
	CHAT_CONTENT		VARCHAR2(1000)  NOT NULL,
	CHAT_REGDATE 		DATE			NOT NULL
	
);

SELECT CHAT_SEQ, MEMBER_ID, MEMBER_NAME, CHAT_CONTENT, CHAT_REGDATE
FROM CHAT
WHERE CHANNEL_NUM = 1
ORDER BY CHAT_REGDATE;

INSERT INTO CHAT
VALUES (CHATSEQ.NEXTVAL, 1, 'admin', 'admin', '채팅로그테스트 전체채팅방 admin', SYSDATE);

INSERT INTO CHAT
VALUES (CHATSEQ.NEXTVAL, 2, 'admin', 'admin', '채팅로그테스트 2번채팅방 admin', SYSDATE);

INSERT INTO CHAT
VALUES (CHATSEQ.NEXTVAL, 3, 'admin', 'admin', '채팅로그테스트 3번채팅방 admin', SYSDATE);

INSERT INTO CHAT
VALUES (CHATSEQ.NEXTVAL, 4, 'admin', 'admin', '채팅로그테스트 4번채팅방 admin', SYSDATE);

INSERT INTO CHAT
VALUES (CHATSEQ.NEXTVAL, 1, '11', '11', '채팅로그테스트 11', SYSDATE);

INSERT INTO CHAT
VALUES (CHATSEQ.NEXTVAL, 2, '11', '11', '채팅로그테스트 전체채팅방 2번채팅방 11', SYSDATE);

INSERT INTO CHAT
VALUES (CHATSEQ.NEXTVAL, 3, '11', '11', '채팅로그테스트 전체채팅방 3번채팅방 11', SYSDATE);

INSERT INTO CHAT
VALUES (CHATSEQ.NEXTVAL, 4, '11', '11', '채팅로그테스트 전체채팅방 4번채팅방 11', SYSDATE);

INSERT INTO CHAT
VALUES (CHATSEQ.NEXTVAL, 1, '55', '55', '채팅로그테스트 55', SYSDATE);

INSERT INTO CHAT
VALUES (CHATSEQ.NEXTVAL, 2, '55', '55', '채팅로그테스트 2번채팅방 55', SYSDATE);

INSERT INTO CHAT
VALUES (CHATSEQ.NEXTVAL, 3, '55', '55', '채팅로그테스트 3번채팅방 55', SYSDATE);

INSERT INTO CHAT
VALUES (CHATSEQ.NEXTVAL, 4, '55', '55', '채팅로그테스트 4번채팅방 55', SYSDATE);


