SELECT 
MEMBER_NUM, 
MEMBER_ID, 
MEMBER_PW, 
MEMBER_NAME,
MEMBER_EMAIL, 
MEMBER_PHONE,
MEMBER_PSCODE, 
MEMBER_ADDR, 
MEMBER_ADDRDT,
MEMBER_TYPE, 
MEMBER_AUTH, 
MEMBER_DATE,
MEMBER_ENABLED, 
MEMBER_STATEMENT
FROM MEMBER
WHERE MEMBER_ID = 'admin' 
AND MEMBER_PW = 'admin';