DROP SEQUENCE MESSAGESEQ;
DROP TABLE MESSAGE;

CREATE SEQUENCE MESSAGESEQ;
CREATE TABLE MESSAGE (
	
	MESSAGE_NUM		INT				PRIMARY KEY,
	MSGROOM_NUM		INT				NOT NULL,
	TO_ID			VARCHAR2(50)	NOT NULL,
	FROM_ID			VARCHAR2(50)	NOT NULL,
	CONTENT			VARCHAR2(4000)	NOT NULL,
	MESSAGE_REGDATE DATE			NOT NULL

);

SELECT MESSAGE_NUM, MSGROOM_NUM, TO_ID, FROM_ID, CONTENT, MESSAGE_REGDATE
FROM MESSAGE
ORDER BY MESSAGE_NUM DESC;
