DROP SEQUENCE ALA_SEQ;
DROP TABLE ALARM;


CREATE SEQUENCE ALA_SEQ;
CREATE TABLE ALARM(

	ALA_SEQ INT NOT NULL,
	MEMBER_NUM INT NOT NULL,
	LASTCHAT_NUM INT NOT NULL
	
	
);

CREATE TABLE ALARM(

	ALA_SEQ INT NOT NULL,
	MEMBER_NUM INT NOU NULL,
	LASTCHAT_NUM INT NOT NULL,
	FROM_ID VARCHAR2(500) NOT NULL,
	CONTENT_NUM INT NOU NULL,
	CONTENT VARCHAR2(1000) NOT NULL,
	MESSAGE_REGDATE DATE NOT NULL
	
	
);


SELECT B.FROM_ID, B.CONTENT, B.MESSAGE_REGDATE
FROM MESSAGE M, ALARM A
WHERE 

INSERT INTO ALARM
VALUES('탈주닌자','저 내일 탈주해요..',SYSDATE);


INSERT INTO ALARM
VALUES('인생이란','무엇인가',SYSDATE);


INSERT INTO ALARM
VALUES('목요일엔','뭐먹지',SYSDATE);


SELECT MEMBER_NAME, ALA_CONTENT, TO_CHAR(ALA_REGDATE, 'PM HH24:MI')
FROM ALARM
ORDER BY ALA_REGDATE DESC;

SELECT ALA_REGDATE
FROM ALARM;

SELECT TO_CHAR(ALA_REDGATE, 'PM HH24:MI:SS') FROM ALARM;

SELECT SUBSTR(ALA_REGDATE, 12,6) FROM ALARM;

SELECT TO_CHAR(ALA_REGDATE, 'HH:MM') FROM ALARM;

SELECT MEMBER_NAME, ALA_CONTENT, ALA_REGDATE
FROM ALARM
WHERE ALA_REGDATE = (SELECT MAX(ALA_DATE)
  					 FROM ALARM
  					 WHERE MEMBER_NAME = #{MEMBER_NAME});
  					 
SELECT * 
FROM
(SELECT * FROM ALARM ORDER BY ALA_REGDATE DESC) 
GROUP BY MEMBER_NAME;					 

SELECT * 
FROM ALARM 
WHERE (MEMBER_NAME) IN(
	SELECT MEMBER_NAME,  MAX(ALA_REGDATE)
	FROM ALARM GROUP BY MEMBER_NAME 
)
ORDER BY ALA_REGDATE DESC; 


SELECT * FROM ALARM
WHERE (SELECT * FROM ALARM GROUP BY MEMBER_NAME);


SELECT MAX(ALA_REGDATE)
FROM ALARM;


SELECT MEMBER_NAME, ALA_CONTENT, ALA_REGDATE
FROM ALARM, MESSAGE
WHERE MEMBER_NAME = FROM_ID
AND ALA_REGDATE = MESSAGE_REGDATE;


SELECT MEMBER_NAME, ALA_CONTENT, ALA_REGDATE
FROM ALARM, MESSAGE
WHERE MEMBER_NAME = FROM_ID
AND ALA_REGDATE = MESSAGE_REGDATE;


SELECT FROM_ID, CONTENT, MESSAGE_REGDATE
FROM MESSAGE;


SELECT * 
FROM ALARM, MESSAGE;

SELECT MEMBER_NAME, ALA_CONTENT, ALA_REGDATE
FROM ALARM FULL OUTER JOIN MESSAGE;
USING (MESSAGE_NUM)

SELECT B.FROM_ID, B.CONTENT, B.MESSAGE_REGDATE
FROM ALARM A LETF OUTER JOIN MESSAGE B
ON A.MESSAGE_NUM = B.MESSAGE_NUM;

