DROP TABLE CHANNELMEMBER;
DROP SEQUENCE CHANNELMEMBERSEQ;

CREATE SEQUENCE CHANNELMEMBERSEQ;
CREATE TABLE CHANNELMEMBER (
	
	CHANNELMEMBER_SEQ	INT			 	 NOT NULL,
	CHANNEL_SEQ			INT		   	 	 NOT NULL,
	CHANNEL_NAME 		VARCHAR2(100) 	 NOT NULL,
	MEMBER_ID 			VARCHAR2(50) 	 NOT NULL,
	MEMBER_NAME			VARCHAR2(50) 	 NOT NULL,
	REGDATE				DATE			 NOT NULL
	
	CONSTRAINT CHANNELMEMBER_PK PRIMARY KEY (CHANNELMEMBER_SEQ),
	CONSTRAINT CHANNELMEMBER_FK FOREIGN KEY(CHANNEL_SEQ) REFERENCES CHANNEL(CHANNEL_SEQ)
	
);

SELECT * FROM CHANNELMEMBER;