DROP TABLE CHANNEL;
DROP SEQUENCE CHANNELSEQ;

CREATE SEQUENCE CHANNELSEQ;
CREATE TABLE CHANNEL (
	
	CHANNEL_SEQ			INT 				NOT NULL,
	WORKSPACE_SEQ		INT					NOT NULL,
	CHANNEL_NAME 		VARCHAR2(100) 		NOT NULL,
	CHANNEL_INFORMATION VARCHAR2(1000)	 	NOT NULL,
	MEMBER_ID			VARCHAR2(50)		NOT NULL,
	CHANNEL_ACCESS		VARCHAR2(10)		NOT NULL,
	CHANNEL_ENABLED 	VARCHAR2(2) 		NOT NULL,
	CHANNEL_REGDATE 	DATE 				NOT NULL,
	
	CONSTRAINT CHANNEL_PK PRIMARY KEY (CHANNEL_SEQ),
	CONSTRAINT CHANNEL_ENABLED_CHK CHECK (CHANNEL_ENABLED IN ('Y','N')),
	CONSTRAINT CHANNEL_FK FOREIGN KEY(WORKSPACE_SEQ) REFERENCES WORKSPACE(WORKSPACE_SEQ)

);

SELECT * FROM CHANNEL
ORDER BY CHANNEL_SEQ;