DROP SEQUENCE WORKSPACEMEMBERSEQ;
DROP TABLE WORKSPACEMEMBER;

CREATE SEQUENCE WORKSPACEMEMBERSEQ;
CREATE TABLE WORKSPACEMEMBER (
	
	WORKSPACEMEMBER_SEQ 	INT 				NOT NULL,
	WORKSPACE_SEQ 			INT 				NOT NULL,
	WORKSPACE_NAME 			VARCHAR2(100) 		NOT NULL,
	MEMBER_ID				VARCHAR2(50)		NOT NULL,
	MEMBER_NAME 			VARCHAR2(20)	 	NOT NULL,
	WORKSPACE_REGDATE		DATE 				NOT NULL

	CONSTRAINT WORKSPACEMEMBER_PK PRIMARY KEY(WORKSPACEMEMBER_SEQ),
	CONSTRAINT WORKSPACEMEMBER_FK FOREIGN KEY(WORKSPACE_SEQ) REFERENCES WORKSPACE(WORKSPACE_SEQ)
	
);
