DROP TABLE MEMBER;
DROP SEQUENCE MEMBERSEQ;

CREATE SEQUENCE MEMBERSEQ;

CREATE TABLE MEMBER
(
    MEMBER_NUM        INT               NOT NULL, 
    MEMBER_ID         VARCHAR2(50)      NOT NULL, 
    MEMBER_PW         VARCHAR2(300)     NOT NULL, 
    MEMBER_NAME       VARCHAR2(20)      NOT NULL, 
    MEMBER_EMAIL      VARCHAR2(50)      NOT NULL, 
    MEMBER_PHONE      VARCHAR2(20)      NULL,
    MEMBER_PSCODE     VARCHAR2(10)      NULL,
    MEMBER_ADDR       VARCHAR2(200)     NULL,
    MEMBER_ADDRDT     VARCHAR2(300)     NULL,
    MEMBER_TYPE       VARCHAR2(10)      NULL, 
    MEMBER_AUTH       VARCHAR2(300)     NULL, 
    MEMBER_DATE       DATE              NULL, 
    MEMBER_ENABLED    VARCHAR2(2)       NULL,
    MEMBER_STATEMENT  VARCHAR2(2)       NULL,
    CONSTRAINT MEMBER_PK PRIMARY KEY (MEMBER_NUM)
);

SELECT * FROM MEMBER;
