DROP TABLE ROOMMEMBER;
DROP SEQUENCE ROOMMEMBERSEQ;

CREATE SEQUENCE ROOMMEMBERSEQ;
CREATE TABLE ROOMMEMBER (
	
	ROOMMEMBERSEQ	INT				 PRIMARY KEY,
	CHANNEL_NAME 	VARCHAR2(100) 	 NOT NULL,
	MEMBER_ID 		VARCHAR2(50) 	 NOT NULL,
	REGDATE			DATE			 NOT NULL
	
);

INSERT INTO ROOMMEMBER 
VALUES (ROOMMEMBERSEQ.NEXTVAL,'전체채팅방', '11', SYSDATE);

INSERT INTO ROOMMEMBER 
VALUES (ROOMMEMBERSEQ.NEXTVAL,'채널테스트', '11', SYSDATE);

INSERT INTO ROOMMEMBER 
VALUES (ROOMMEMBERSEQ.NEXTVAL,'채널테스트', '55', SYSDATE);

INSERT INTO ROOMMEMBER 
VALUES (ROOMMEMBERSEQ.NEXTVAL,'전체채팅방', '55', SYSDATE);

INSERT INTO ROOMMEMBER 
VALUES (ROOMMEMBERSEQ.NEXTVAL,'전체', '55', SYSDATE);

SELECT * FROM ROOMMEMBER;